name: 'my_dbt_snowflake_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]
packages-install-path: packages

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  my_dbt_snowflake_project:
    +materialized: view  # Default materialization
    +snowflake_warehouse: pc_dbt_wh  # Default warehouse

    marts:
      +materialized: table
      +snowflake_warehouse: pc_dbt_wh_large
      +schema: "mart"
      +tags: ["mart"]
      +meta:
        contains_pii: false
      core:
        +tags: ["core"]

    staging:
      +materialized: view
      +snowflake_warehouse: pc_dbt_wh
      +schema: "stg"
      +tags: ["staging"]
      +meta:
        contains_pii: false